name: Build

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: blocknetdx/devbuilds:gitlab-linux
    steps:
      - uses: actions/checkout@v4
        if: github.event.pull_request.draft == false

      - run: | 
          echo $GITHUB_WORKSPACE
          echo $PROJECTDIR
          echo $PWD

      - run: |
          export PROJECTDIR=/opt/blocknetdx/blocknet
          export BASEPREFIX=$PROJECTDIR/depends
          export BASEPREFIX_CACHE=/proj/depends-cache
          export DISTDIR=$PROJECTDIR/dist
          export HOST=x86_64-pc-linux-gnu
          rm -rf $BASEPREFIX
          mv $BASEPREFIX_CACHE $BASEPREFIX
          mkdir -p $DISTDIR
          chmod +x ./autogen.sh; sync
          ./autogen.sh
          CONFIG_SITE="$BASEPREFIX/$HOST/share/config.site" ./configure CC=gcc-8 CXX=g++-8 CFLAGS="-g3 -O0" CXXFLAGS="-g3 -O0" --enable-debug --prefix=/
          make clean
          make -j $(nproc)
          make install DESTDIR=$DISTDIR

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts-linux
          path: |
            dist/bin/blocknet-cli
            dist/bin/blocknetd
            dist/bin/blocknet-qt
            dist/bin/blocknet-tx
            dist/bin/blocknet-wallet
            dist/bin/test_blocknet
            dist/bin/test_blocknet-qt
